### ISSUE TITLE
Whitesmith skills are wrong

### ISSUE THREAD

**Issue by al3xastakhov** [gabaeba/mom-build-planner#5]
* Axe tornado is now max 5 lvls (10 in the planner)
* Full adrenaline rush is missing
* Weapon craft skills no longer there

Not sure if list is exhaustive

**Comment by gabaeba** [comment]
Thank you for the report, i've fixed item 1 and 2, but as for item 3, I'm not sure what you're talking about, the craft skills were removed from bs/ws.

**Comment by al3xastakhov** [comment]
Exactly!
That's why you should remove them from the configurator too :-)
![image](https://github.com/gabaeba/mom-build-planner/assets/3749550/44f692de-aaa5-42f8-9902-51f76000416f)

**Comment by al3xastakhov** [comment]
Also, "Full Adrenalin Rush" has 5 lvls (1 in the planner)

**Comment by gabaeba** [comment]
Thanks! Fixed those.

**Comment by gabaeba** [comment]
Closing this issue, please open another one if there's anything missing.
